[package]
name = "barcode_sound"
version = "0.1.0"
authors = ["sbock <sebastian.bockholt@rwth-aachen.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4.0"
structopt = "0.3"
